run creds grab from environment

diff --git a/environment b/environment
--- a/environment
+++ b/environment
@@ -58,7 +58,6 @@ DSS_GS_CHECKOUT_BUCKET_PROD=org-humancellatlas-dss-checkout-prod
 DSS_NOTIFICATION_SENDER="DSS Notifier <dss.humancellatlas@gmail.com>"
 GOOGLE_APPLICATION_CREDENTIALS="${DSS_HOME}/gcp-credentials.json"
 GOOGLE_APPLICATION_SECRETS="${DSS_HOME}/application_secrets.json"
-ADMIN_USER_EMAILS=`jq ".client_email" ${GOOGLE_APPLICATION_CREDENTIALS} | sed 's/"//g'` || ADMIN_USER_EMAILS=""
 API_DOMAIN_NAME=dss.dev.data.humancellatlas.org
 TOKENINFO_URL=https://${API_DOMAIN_NAME}/internal/tokeninfo
 NOTIFY_URL=https://${API_DOMAIN_NAME}/internal/notify
@@ -92,3 +91,6 @@ set +a
 if [[ -f "${DSS_HOME}/environment.local" ]]; then
     source "${DSS_HOME}/environment.local"
 fi
+
+scripts/get_gcp_credentials.py || echo "Unable to recover gcp credentials from Secrets Manager. Your configuratoin is incorrect/incomplete."
+export ADMIN_USER_EMAILS=`jq ".client_email" ${GOOGLE_APPLICATION_CREDENTIALS} | sed 's/"//g'` || ADMIN_USER_EMAILS=""
